In [12]:
import numpy as np


x = np.array([1,2,3])
print(f"Dimension {x.ndim}")
print(x)
print(x.shape)

y = np.array([[1,2,3], [4,5,6]])
print(f"Dimension {y.ndim}")
print(y)
print(y.shape)

list_z = [[[0] * 3] * 3] * 3


z = np.array(list_z)
print(f"Dimension {z.ndim}")
print(z)
print(z.shape)

Dimension 1
[1 2 3]
(3,)
Dimension 2
[[1 2 3]
 [4 5 6]]
(2, 3)
Dimension 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
(3, 3, 3)


In [15]:
A = np.array([[1,2,3], [4,5,6]])
b = np.array([10, 20, 30])

A*b

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [16]:
# 
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a, b)

32

In [18]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
print(np.dot(A, B))

[[19 22]
 [43 50]]


ニューラネットワークの推論

全結合層


入力層

隠れ層（中間層）

出力層

In [ ]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))